name: slide
description: A Flutter package which implements a backdrop displaying contextual and actionable content. =]
version: 2.4.0
homepage: https://github.com/luciano-work/we_slide

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
flutter:
